#!/usr/bin/env python3
"""Independent reference values for the decay test cases (TEST_CASES.md).

Expected values are produced outside the toolkit, from the formulas of
docs/methodology/MODEL_CONTRACTS.md (decay model and regulatory overlay):
closed forms, numpy least squares and scipy distributions. Nothing here is
derived from, or shares code with, the VBA engine.

Usage:
    python tests/expected/decay/make_expected.py             # write *.json
    python tests/expected/decay/make_expected.py --emit-vba  # also regenerate
                                                             # tests/modules/TEST_DecayData.bas
"""
from __future__ import annotations

import csv
import json
import math
import platform
import sys
from datetime import date
from pathlib import Path

import numpy as np
import scipy
from scipy import stats

ROOT = Path(__file__).resolve().parents[3]
HERE = Path(__file__).resolve().parent
FIX = ROOT / "tests" / "fixtures" / "decay"
VBA = ROOT / "tests" / "modules" / "TEST_DecayData.bas"

PROVENANCE = {
    "tool": f"Python {platform.python_version()}, numpy {np.__version__}, scipy {scipy.__version__}",
    "script": "tests/expected/decay/make_expected.py",
    "date": "2026-10-08",
    "produced_by": "Generated by the committed script for the maintainer (Daniele Penza); not yet reviewed",
}
REG1 = {"RET_TX": (0.90, 60.0), "RET_NTX": (0.70, 54.0), "WHS_NFC": (0.50, 48.0)}


def read_series(name: str) -> tuple[list[date], list[float]]:
    rows = list(csv.DictReader((FIX / name).open(encoding="ascii")))
    return [date.fromisoformat(r["as_of_date"]) for r in rows], [float(r["balance"]) for r in rows]


# ---------------------------------------------------------------- closed forms
def estimate_closed_form(g: list[float], breaks: list[int]) -> dict:
    """Impulse dummies at 0-based positions: OLS has the closed form
    mu = mean of non-break g, kappa_j = g_j - mu, sigma^2 = SSR / (n - 1 - K)."""
    n, k = len(g), len(breaks)
    keep = [x for i, x in enumerate(g) if i not in breaks]
    mu = math.fsum(keep) / len(keep)
    resid = [0.0 if i in breaks else x - mu for i, x in enumerate(g)]
    sigma = math.sqrt(math.fsum(r * r for r in resid) / (n - 1 - k))
    return {"mu_hat": mu, "sigma": sigma, "kappa": [g[i] - mu for i in breaks], "resid": resid}


def profile(b0: float, mu_star: float, sigma: float, z: float, cutoff: int) -> dict:
    mpa = [b0 * math.exp(mu_star * h + z * sigma * math.sqrt(h)) for h in range(cutoff + 1)]
    runoff = [mpa[h - 1] - mpa[h] for h in range(1, cutoff + 1)]
    life_sum = math.fsum(h * runoff[h - 1] for h in range(1, cutoff + 1)) + cutoff * mpa[cutoff]
    core_sum = math.fsum(h * runoff[h - 1] for h in range(2, cutoff + 1)) + cutoff * mpa[cutoff]
    return {"mpa": mpa, "runoff": runoff, "remainder": mpa[cutoff],
            "median": [b0 * math.exp(mu_star * h) for h in range(cutoff + 1)],
            "noncore_share": 1 - mpa[1] / b0, "core": mpa[1],
            "mean_life": life_sum / b0, "core_mean_life": core_sum / mpa[1]}


def overlay(segment: str, mpa: list[float]) -> dict:
    share_cap, mat_cap = REG1[segment]
    b0, cutoff = mpa[0], len(mpa) - 1
    scale = share_cap * b0 / mpa[1] if mpa[1] / b0 > share_cap else 1.0
    c = [scale * x for x in mpa]

    def life(hc: int) -> float:
        return (math.fsum(h * (c[h - 1] - c[h]) for h in range(2, hc + 1)) + hc * c[hc]) / c[1]

    life_in = life(cutoff)
    hc = cutoff
    if life_in > mat_cap:
        hc = max(h for h in range(1, cutoff + 1) if life(h) <= mat_cap)
    buckets = [0.0] * (cutoff + 1)
    buckets[0] = b0 - c[1]
    for h in range(2, hc + 1):
        buckets[h] = c[h - 1] - c[h]
    buckets[hc] += c[hc]
    return {"buckets": buckets, "scale": scale, "share_applied": int(scale != 1.0),
            "core_share": c[1] / b0, "core_mean_life_in": life_in, "cutoff": hc,
            "mat_applied": int(life_in > mat_cap), "core_mean_life": life(hc), "overnight": buckets[0],
            "share_cap": share_cap, "mat_cap": mat_cap}


def ljung_box(e: np.ndarray, lags: int) -> tuple[float, float]:
    n = len(e)
    d = e - e.mean()
    den = float(d @ d)
    q = sum((float(d[k:] @ d[:-k]) / den) ** 2 / (n - k) for k in range(1, lags + 1))
    q *= n * (n + 2)
    return q, float(stats.chi2.sf(q, lags))


def backtest(dates, bal, origin_idx, end_idx, mu_star, sigma, z, max_h) -> dict:
    pairs = [0] * max_h
    exceed = [0] * max_h
    origins = 0
    for u in range(origin_idx + 1, end_idx):
        scored = False
        for h in range(1, max_h + 1):
            if u + h > end_idx:
                break
            level = bal[u] * math.exp(mu_star * h + z * sigma * math.sqrt(h))
            pairs[h - 1] += 1
            exceed[h - 1] += int(bal[u + h] < level)
            scored = True
        origins += int(scored)
    return {"pairs": pairs, "exceed": exceed, "origins": origins, "total_pairs": sum(pairs),
            "total_exceed": sum(exceed), "rate": sum(exceed) / sum(pairs)}


# ---------------------------------------------------------------- cases
def case(case_id: str, checks: str, method: str, tol_kind: str, eps: float, inputs: dict, expected: dict,
         fixture: str | None = None) -> dict:
    out = {"case": case_id, "checks": checks, "provenance": dict(PROVENANCE, method=method)}
    if fixture:
        out["fixture"] = fixture
    out.update({"tolerance": {"kind": tol_kind, "eps": eps}, "inputs": inputs, "expected": expected})
    return out


def build() -> list[dict]:
    cases = []

    # DEC-LOG-01 -------------------------------------------------------------
    _, short = read_series("dec_log_short.csv")
    g = [math.log(short[i]) - math.log(short[i - 1]) for i in range(1, len(short))]
    no_break = estimate_closed_form(g, [])
    with_break = estimate_closed_form(g, [3])  # log change ending 2025-05-31
    cases.append(case("DEC-LOG-01", "Log changes, mu, sigma with and without one break dummy",
                      "Closed-form OLS with impulse dummies (mean of non-break changes), math.log/fsum",
                      "abs", 1e-12, {"break_dates": ["2025-05-31"]},
                      {"g": g, "nobreak_mu": no_break["mu_hat"], "nobreak_sigma": no_break["sigma"],
                       "break_mu": with_break["mu_hat"], "break_sigma": with_break["sigma"],
                       "break_kappa": with_break["kappa"][0], "break_resid": with_break["resid"]},
                      "tests/fixtures/decay/dec_log_short.csv"))

    # DEC-MPA-01 -------------------------------------------------------------
    b0, mu_star, sigma, conf = 1_000_000.0, -0.0015, 0.018, 0.99
    z = float(stats.norm.ppf(1.0 - conf))
    p = profile(b0, mu_star, sigma, z, 120)
    cases.append(case("DEC-MPA-01", "MPA(h), h = 0..120, and z = Phi^-1(1 - c)",
                      "Closed form with scipy.stats.norm.ppf", "rel", 1e-10,
                      {"b0": b0, "mu_star": mu_star, "sigma": sigma, "confidence": conf, "cutoff": 120},
                      {"z": z, "mpa": p["mpa"]}))

    # DEC-PROF-01 and DEC-LIFE-01 ---------------------------------------------
    hand = {"b0": 1000.0, "mu_star": -0.01, "sigma": 0.02, "z": -2.0, "cutoff": 6}
    hp = profile(hand["b0"], hand["mu_star"], hand["sigma"], hand["z"], hand["cutoff"])
    cases.append(case("DEC-PROF-01", "Runoff, remainder, notional conservation, monotonicity",
                      "Direct evaluation of the contract formulas (math.exp)", "abs", 1e-8, hand,
                      {"mpa": hp["mpa"], "runoff": hp["runoff"], "remainder": hp["remainder"],
                       "sum": math.fsum(hp["runoff"]) + hp["remainder"]}))
    cases.append(case("DEC-LIFE-01", "Mean life of the profile and of the core (months)",
                      "Direct evaluation of the contract formulas", "abs", 1e-9, hand,
                      {"mean_life": hp["mean_life"], "core_mean_life": hp["core_mean_life"],
                       "noncore_share": hp["noncore_share"]}))

    # DEC-CAP-01 ---------------------------------------------------------------
    cap_inputs = [("RET_TX", 1000.0, 0.0, 0.005, -2.326, 120),
                  ("WHS_NFC", 1000.0, -0.03, 0.05, -2.33, 120),
                  ("RET_NTX", 1000.0, -0.02, 0.15, -2.33, 120)]
    cap_expected = {}
    for i, (seg, cb0, cmu, csig, cz, ch) in enumerate(cap_inputs, 1):
        ov = overlay(seg, profile(cb0, cmu, csig, cz, ch)["mpa"])
        cap_expected[f"case{i}"] = ov
    cases.append(case("DEC-CAP-01", "Overlay: non-core overnight, core-share scaling, cutoff reduction",
                      "Direct implementation of the overlay rules with REG-1 Table 2 caps (verified)",
                      "abs", 1e-8,
                      {f"case{i}": {"segment": s, "b0": a, "mu_star": m, "sigma": sg, "z": zz, "cutoff": hh}
                       for i, (s, a, m, sg, zz, hh) in enumerate(cap_inputs, 1)}, cap_expected))

    # DEC-E2E-01 ---------------------------------------------------------------
    dates, bal = read_series("dec_series_ret_tx.csv")
    est_end = date(2022, 12, 31)
    test_end = date(2025, 12, 31)
    e = max(i for i, d in enumerate(dates) if d <= est_end)
    f = max(i for i, d in enumerate(dates) if d <= test_end)
    g = np.diff(np.log(np.array(bal[:e + 1])))
    brk = [i - 1 for i, d in enumerate(dates) if d == date(2020, 3, 31)]
    X = np.column_stack([np.ones(len(g))] + [np.eye(len(g))[:, j] for j in brk])
    beta, *_ = np.linalg.lstsq(X, g, rcond=None)
    resid = g - X @ beta
    sig = math.sqrt(float(resid @ resid) / (len(g) - 1 - len(brk)))
    conf, cutoff = 0.99, 120
    zz = float(stats.norm.ppf(1.0 - conf))
    ms = min(float(beta[0]), 0.0)
    ep = profile(bal[e], ms, sig, zz, cutoff)
    q, qp = ljung_box(resid, 12)
    jb = stats.jarque_bera(resid)
    skew = float(stats.skew(resid))
    kurt = float(stats.kurtosis(resid, fisher=False))
    emp = float(np.quantile(resid / sig, 1.0 - conf, method="linear"))
    ov = overlay("RET_TX", ep["mpa"])
    bt = backtest(dates, bal, e, f, ms, sig, zz, 12)
    cases.append(case("DEC-E2E-01", "Full fit with one break, diagnostics, overlay and 12-horizon backtest",
                      "numpy.linalg.lstsq; scipy.stats norm.ppf, chi2.sf, jarque_bera, skew, kurtosis; "
                      "numpy.quantile(method='linear'); contract formulas for profile, overlay and scoring",
                      "rel", 1e-9,
                      {"segment": "RET_TX", "currency": "EUR", "est_start": dates[0].isoformat(),
                       "est_end": est_end.isoformat(), "test_end": test_end.isoformat(),
                       "break_dates": ["2020-03-31"], "confidence": conf, "cutoff": cutoff, "max_horizon": 12},
                      {"n": len(g), "mu_hat": float(beta[0]), "kappa": float(beta[1]), "sigma": sig, "z": zz,
                       "mu_star": ms, "b0": bal[e], "mpa1": ep["mpa"][1], "mpa12": ep["mpa"][12],
                       "mpa60": ep["mpa"][60], "mpa120": ep["mpa"][120], "noncore_share": ep["noncore_share"],
                       "mean_life": ep["mean_life"], "core_mean_life": ep["core_mean_life"],
                       "lb_q": q, "lb_p": qp, "jb": float(jb.statistic), "jb_p": float(jb.pvalue),
                       "skew": skew, "kurt": kurt, "emp_q": emp,
                       "ov_scale": ov["scale"], "ov_cutoff": ov["cutoff"], "ov_overnight": ov["overnight"],
                       "ov_core_mean_life": ov["core_mean_life"],
                       "bt_origins": bt["origins"], "bt_pairs": bt["total_pairs"], "bt_exceed": bt["total_exceed"],
                       "bt_rate": bt["rate"], "bt_pairs_by_h": bt["pairs"], "bt_exceed_by_h": bt["exceed"]},
                      "tests/fixtures/decay/dec_series_ret_tx.csv"))

    # OOS-SCORE-01 (decay exceedance part) --------------------------------------
    oos_dates = ["2025-06-30", "2025-07-31", "2025-08-31", "2025-09-30", "2025-10-31", "2025-11-30", "2025-12-31"]
    oos_bal = [1000.0, 1000.0, 950.0, 990.0, 930.0, 960.0, 900.0]
    obt = backtest(oos_dates, oos_bal, 0, len(oos_bal) - 1, -0.01, 0.02, -2.0, 3)
    cases.append(case("OOS-SCORE-01", "Decay exceedance rate on a hand case (rate scores: NOT BUILT)",
                      "Direct counting of (origin, horizon) pairs per the out-of-sample contract",
                      "abs", 1e-12,
                      {"dates": oos_dates, "balances": oos_bal, "origin": "2025-06-30", "mu_star": -0.01,
                       "sigma": 0.02, "z": -2.0, "confidence": 0.99, "max_horizon": 3},
                      {"pairs_by_h": obt["pairs"], "exceed_by_h": obt["exceed"], "origins": obt["origins"],
                       "pairs": obt["total_pairs"], "exceed": obt["total_exceed"], "rate": obt["rate"]}))
    return cases


# ---------------------------------------------------------------- VBA emitter
def vnum(x: float) -> str:
    return f'Val("{repr(float(x)).upper()}")'


def vdate(iso: str) -> str:
    d = date.fromisoformat(iso)
    return f"DateSerial({d.year}, {d.month}, {d.day})"


def flatten(prefix: str, value) -> list[tuple[str, float]]:
    if isinstance(value, dict):
        out = []
        for k, v in value.items():
            out += flatten(f"{prefix}.{k}" if prefix else k, v)
        return out
    if isinstance(value, list):
        out = []
        for i, v in enumerate(value):
            out += flatten(f"{prefix}[{i}]", v)
        return out
    return [(prefix, float(value))]


def flatten_any(prefix: str, value) -> list[tuple[str, object]]:
    if isinstance(value, dict):
        out = []
        for k, v in value.items():
            out += flatten_any(f"{prefix}.{k}" if prefix else k, v)
        return out
    if isinstance(value, list):
        out = []
        for i, v in enumerate(value):
            out += flatten_any(f"{prefix}[{i}]", v)
        return out
    return [(prefix, value)]


def vany(value) -> str:
    if isinstance(value, bool):
        return "True" if value else "False"
    if isinstance(value, (int, float)):
        return vnum(value)
    text = str(value)
    try:
        date.fromisoformat(text)
        return vdate(text)
    except ValueError:
        return '"' + text.replace('"', '""') + '"'


def emit_vba(cases: list[dict]) -> str:
    rows = []
    for c in cases:
        for key, val in flatten("", c["expected"]):
            rows.append((c["case"], key, val, c["tolerance"]["kind"], c["tolerance"]["eps"]))
    lines = [
        'Attribute VB_Name = "TEST_DecayData"',
        "'==============================================================================",
        "' TEST_DecayData  (GENERATED - do not edit by hand)",
        "'------------------------------------------------------------------------------",
        "' Fixtures and independent expected values for the decay cases, generated by",
        "' tests/expected/decay/make_expected.py --emit-vba from tests/fixtures/decay/",
        "' and tests/expected/decay/*.json. Numbers use Val() (locale-independent).",
        "'==============================================================================",
        "Option Explicit",
        "Option Private Module",
        "",
    ]
    chunk = 100  # keeps every generated procedure far below the VBA 64 KB limit
    parts = [rows[i:i + chunk] for i in range(0, len(rows), chunk)]
    lines += ["Public Function TEST_DecayExpected() As Variant",
              "    ' (n, 1 To 5): case ID, key, expected value, tolerance kind, epsilon.",
              "    Dim v() As Variant",
              f"    ReDim v(1 To {len(rows)}, 1 To 5)"]
    lines += [f"    ExpectedPart{k + 1} v" for k in range(len(parts))]
    lines += ["    TEST_DecayExpected = v", "End Function", ""]
    start = 1
    for k, part in enumerate(parts):
        lines.append(f"Private Sub ExpectedPart{k + 1}(ByRef v() As Variant)")
        for i, (cid, key, val, kind, eps) in enumerate(part, start):
            lines.append(f'    v({i}, 1) = "{cid}": v({i}, 2) = "{key}": v({i}, 3) = {vnum(val)}: '
                         f'v({i}, 4) = "{kind}": v({i}, 5) = {vnum(eps)}')
        lines += ["End Sub", ""]
        start += len(part)
    inputs = []
    for c in cases:
        for key, val in flatten_any("", c["inputs"]):
            inputs.append((c["case"], key, val))
    lines += ["Public Function TEST_DecayInputs() As Variant",
              "    ' (n, 1 To 3): case ID, key, value (Double, Date or String).",
              "    Dim v() As Variant",
              f"    ReDim v(1 To {len(inputs)}, 1 To 3)"]
    for i, (cid, key, val) in enumerate(inputs, 1):
        lines.append(f'    v({i}, 1) = "{cid}": v({i}, 2) = "{key}": v({i}, 3) = {vany(val)}')
    lines += ["    TEST_DecayInputs = v", "End Function", ""]
    for name, fname in (("Short", "dec_log_short.csv"), ("RetTx", "dec_series_ret_tx.csv")):
        dates, bal = read_series(fname)
        lines += [f"Public Sub TEST_Fixture{name}(ByRef dates() As Date, ByRef balances() As Double)",
                  f"    ' {fname}",
                  f"    ReDim dates(1 To {len(dates)})", f"    ReDim balances(1 To {len(dates)})"]
        for i, (d, b) in enumerate(zip(dates, bal), 1):
            lines.append(f"    dates({i}) = {vdate(d.isoformat())}: balances({i}) = {vnum(b)}")
        lines += ["End Sub", ""]
    return "\r\n".join(lines)


def main() -> int:
    cases = build()
    for c in cases:
        (HERE / f"{c['case']}.json").write_text(json.dumps(c, indent=2) + "\n", encoding="ascii")
    print(f"wrote {len(cases)} expected files")
    if "--emit-vba" in sys.argv:
        VBA.write_bytes(emit_vba(cases).encode("ascii"))
        print(f"wrote {VBA}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
